import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="dscvr:canvas:version" content="vNext"/>
        <meta name="og:image" content="cover.png"></meta>
        <title>DAO&apos;s NFT</title>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
